export const dataList = [
    {
        Laon_No : 'L28U6247',
        Loan_type : 'Home Loan',
        Borrower : 'Vedika Sachar',
        Borrower_address : '83 Yogi Ganj, Kadapa 058720',
        Co_Borrower_1_Name : 'Divit Vora',
        Co_Borrower_1_Address : '24/543, Acharya Path Ongoie-052360',
        Current_DPD : 91,
        Sanction_Amount : 1934068,
        Region : 'West',
        State : 'Uttar Pradesh',
    },
    {
        Laon_No : 'L28K3243',
        Loan_type : 'Car Loan',
        Borrower : 'Hrishita Agrawal',
        Borrower_address : '86/622, Deo Path, Berhampore 841186',
        Co_Borrower_1_Name : 'Mahika Tak',
        Co_Borrower_1_Address : '58 Tella Road, Sultan Marg Pur Majra 919878',
        Current_DPD : 100,
        Sanction_Amount : 1842143,
        Region : 'North',
        State : 'Madhya Pradesh',
    },
    {
        Laon_No : 'L5678UTY0',
        Loan_type : 'Car Loan',
        Borrower : 'Priyansh Soman',
        Borrower_address : 'H.No. 152, Andra Street Amritsar-417162',
        Co_Borrower_1_Name : 'Zaina Dara',
        Co_Borrower_1_Address : 'H.No. 42 Srivastava Marg, Junagadh=191124',
        Current_DPD : 100,
        Sanction_Amount : 4537889,
        Region : 'East',
        State : 'Tamil Nadu',
    },
    {
        Laon_No : 'L9IUYHJ88',
        Loan_type : 'Home Loan',
        Borrower : 'Hrishita Chanda',
        Borrower_address : '24, Ray Chowk Guntakal 809332',
        Co_Borrower_1_Name : 'Zain Ghosh',
        Co_Borrower_1_Address : 'H.No. 59, Dugar Street Bokaro 543900',
        Current_DPD : 100,
        Sanction_Amount : 2681712,
        Region : 'West',
        State : 'Andhra Pradesh',
    },
    {
        Laon_No : 'L48U32J0',
        Loan_type : 'Home Loan',
        Borrower : 'Hrishita Sen',
        Borrower_address : '94/36, barad, Habli Dharwad-408790',
        Co_Borrower_1_Name : 'Shrey Kala',
        Co_Borrower_1_Address : '63/66, Bhardwaj Street Bokaro 662204',
        Current_DPD : 100,
        Sanction_Amount : 4456808,
        Region : 'West',
        State : 'Rajasthan',
    },
    {
        Laon_No : 'L78P7060',
        Loan_type : 'Home Loan',
        Borrower : 'Hrishita Sen',
        Borrower_address : '94/36, barad, Habli Dharwad-408790',
        Co_Borrower_1_Name : 'Shrey Kala',
        Co_Borrower_1_Address : '63/66, Bhardwaj Street Bokaro 662204',
        Current_DPD : 100,
        Sanction_Amount : 4456808,
        Region : 'West',
        State : 'Rajasthan',
    },
    {
        Laon_No : 'L23O3260',
        Loan_type : 'Home Loan',
        Borrower : 'Hrishita Sen',
        Borrower_address : '94/36, barad, Habli Dharwad-408790',
        Co_Borrower_1_Name : 'Shrey Kala',
        Co_Borrower_1_Address : '63/66, Bhardwaj Street Bokaro 662204',
        Current_DPD : 100,
        Sanction_Amount : 4456808,
        Region : 'West',
        State : 'Rajasthan',
    },
    {
        Laon_No : 'L09T3260',
        Loan_type : 'Home Loan',
        Borrower : 'Hrishita Sen',
        Borrower_address : '94/36, barad, Habli Dharwad-408790',
        Co_Borrower_1_Name : 'Shrey Kala',
        Co_Borrower_1_Address : '63/66, Bhardwaj Street Bokaro 662204',
        Current_DPD : 100,
        Sanction_Amount : 4456808,
        Region : 'West',
        State : 'Rajasthan',
    },
    {
        Laon_No : 'G6U3260',
        Loan_type : 'Home Loan',
        Borrower : 'Hrishita Sen',
        Borrower_address : '94/36, barad, Habli Dharwad-408790',
        Co_Borrower_1_Name : 'Shrey Kala',
        Co_Borrower_1_Address : '63/66, Bhardwaj Street Bokaro 662204',
        Current_DPD : 100,
        Sanction_Amount : 4456808,
        Region : 'West',
        State : 'Rajasthan',
    },
    {
        Laon_No : 'L76U3260',
        Loan_type : 'Home Loan',
        Borrower : 'Hrishita Sen',
        Borrower_address : '94/36, barad, Habli Dharwad-408790',
        Co_Borrower_1_Name : 'Shrey Kala',
        Co_Borrower_1_Address : '63/66, Bhardwaj Street Bokaro 662204',
        Current_DPD : 100,
        Sanction_Amount : 4456808,
        Region : 'West',
        State : 'Rajasthan',
    },

]